# greggpt configuration
model_path: "models/tinyllama-1.1b-chat-v1.0.Q2_K.gguf"
docs_dir: "documents"
vectorstore_path: "vectorstore"

# Model parameters
max_tokens: 512
temperature: 0.7
top_p: 0.9

# Chunking settings
chunk_size: 1000
chunk_overlap: 200
